export const Routes = {
  LOGGED: {
    INITIAL: 'Initial',
    HOME: 'Home',
    CLIENTS: 'Clients',
    CREATECLIENTS: 'CreateClients',
    PRODUCTS: 'Products',
    PRODUCTDETAILS: 'ProductDetails',
    USERSCLIENTS: 'UsersClients',
    PROFILE: 'Profile',
    PARTNERPROFILE: 'PartnerProfile',
    POSTERSINITIAL: 'PostersInitial',
    POSTERS: 'Posters',
    MYPOSTERS: 'MyPosters',
    POSTERSPENDING: 'PostersPending',
    CONTACT: 'Contact',
    FAQ: 'Faq',
    LOGOUT: 'Logout',
  },
  UNLOGGED: {
    GETSTARTED: 'GetStarted',
    LOGIN: 'Login',
    CREATEACCOUNT: 'CreateAccount',
  },
};
